// "use client" // must use this is next.js 

import './globals.css'


export const metadata = {
  title: 'React Practice - Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressContentEditableWarning>
        {/* <MyContext.Provider> */}

        {children}
        {/* </MyContext.Provider> */}

        </body>
    </html>
  )
}
