

export const metadata = {
  title: 'React Practice - Contact',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressContentEditableWarning>

        <h1> This is Contact page layout.js</h1>
        {children}
      </body>
    </html>
  )
}
